### ISSUE TITLE
stable-Branch klarmachen

### ISSUE THREAD

**Issue by oliver** [FreifunkBremen/gluon-site-ffhb#12]
Es gibt im Moment den "stable"-Branch (921a16a10ce69772c885ee99d76bdb6422462a05; davon wurde die letzte stable-Firmware gebaut:  [v2015.1.2+bremen2](https://github.com/FreifunkBremen/gluon-site-ffhb/releases/tag/v2015.1.2%2Bbremen2)); und es gibt den "master"-Branch (57e582d5002090cdde75cd4612d5d9e6eb9d7591), auf dem einige aktuelle Config-Änderungen liegen und von dem noch keine Firmware gebaut wurde.

Wenn wir jetzt eine neue stable-Firmware mit weiteren Config-Änderungen bauen wollen: von welchem Branch sollte das dann kommen? Ich finde, wir sollten hierfür den stable-Branch auf einen sauberen Stand bringen, von dem dann bei Bedarf gebaut werden könnte.

Ich denke, die Änderungen auf dem master-Branch sind alle für die stable-Firmware geeignet.  @jplitza @mortzu @xmorpheus @komaflash: seht ihr das auch so?

Außerdem ist 5c2df648af082b27991258308b5e0cc22ab6a3bd ("Remove vpn0[456] again") im Moment für die stable-FW nötig, solange wir VPN4/5/6 nicht in die stable-FW aufnehmen wollen.

**Ich schlage also vor, dass wir auf 57e582d5002090cdde75cd4612d5d9e6eb9d7591 (den master-Branch) noch 5c2df648af082b27991258308b5e0cc22ab6a3bd folgen lassen und das Ergebnis als stable-Branch nehmen.**

Ich könnte das wohl hier im FreifunkBremen-Repo direkt umsetzen (per Pull-Request aus meinem Fork trau ich mir das nicht zu). Kann aber auch gern jemand anders machen.

**Comment by ghost** [comment]
Ich denke vpn04 kann auf jeden Fall rein (ich kann es nur bei dem sagen, da ich den ueberwache und somit mitbekomme wie selten der ausfaellt). Zu den anderen bitte ich um Meinungen

**Comment by jplitza** [comment]
Stimmt wohl alles so. Zur Stabilität von vpn0[56] kann ich auch nix sagen, hätte sie jetzt aber erstmal rausgelassen da wir noch nicht auf nem Treffen beschlossen haben sie aufzunehmen (oder?).

Insgesamt ist das Repo hier im Moment aber ziemlich Kraut und Rüben und bräuchte mal ein Konzept. Vermutlich sollten
- Änderungen, die nicht diskutiert werden müssen, im stable Branch passieren und spätestens beim Bau der nächsten Testing in den master Branch gemerged werden
- Änderungen, die erst mal nur in die Testing sollen, im master Branch geschehen und dann irgendwann entweder reverted oder in den stable Branch gemerged werden

In der aktuellen Situation wäre wohl ein Merge von master nach stable am sinnvollsten, da das ein fast-forward ermöglicht und kein Rewrite der History bedeutet.

**Comment by corny** [comment]
vpn06 ist meiner und der ist aus dem Telekom-Netz sehr gut zu erreichen. Ich hätte ihn schon gerne drin.

**Comment by xmorpheus** [comment]
Zur Software kann ich nicht viel sagen, zum VPN hingegen:

vpn04 => hetzner
vpn05 => noch ein hetzner
vpn06 => gut wegen Telekom

Ich finde eigentlich nur den vpn06 sinnvoll...

**Comment by SimJoSt** [comment]
@jplitza's Vorschlag finde ich gut. Bringt ein bisschen Struktur in das Ganze.
Ich bin dafür bald auch die stable-Knoten auf die neuen VPN-Server loszulassen, jedoch denke ich, dass nicht zu viel auf ein Mal geändert werden sollte.
Lass uns erst mal die aktuellen Änderungen und fixes übernehmen. Eine weitere stable nur wenig später nachzuschieben, ist dann ja kein Aufwand.

**Comment by corny** [comment]
Ich hätte gerne mindestens vpn04 und vpn06 hinzugefügt.

Statt die Telekom doppelt für Traffic zu bezahlen, würde ich lieber eine kleine Website erstellen, mit der jeder Telekom-Kunde unter Angabe seiner Kundendaten ein Beschwerde-Fax an die Telekom verschicken kann. Was haltet ihr davon? Mit Fax-Versand habe ich Erfahrung: https://selbstauskunft.net/

**Comment by genofire** [comment]
jetto möchte vpn05 erst mit offloader in stable übernehmen, im Q1-2016 (mir eigentlich egal).

seit vpn05 verschoben wurde, hat sie etwas rumgezickt, ping ging noch doch manchmal konnte ich nicht mal mehr ssh-verbindungen aufbauen. (in den logs erschienen kernelfehler). Doch seit 1-2 Wochen muss ich sie auch nicht neustarten :D -> daher bitte wirklich erst im Q1-2016 aufnehmen.

**Comment by corny** [comment]
gut, also vpn06 dazu!

**Comment by SimJoSt** [comment]
Ich habe gerade in einem Fork den master in den stable branch gemerged. Die neuen VPN-Server sind nicht übernommen worden. Bitte schaut euch mal den PR an: https://github.com/FreifunkBremen/gluon-site-ffhb/pull/13

Mein Vorschlag ist, eine neue Stable mit diesen ganzen Änderungen zu bauen. Viele sind bugfixes.
Sobald sie ausgerollt wurde und wir sehen, dass diese Änderungen funktionieren, können wir eine mit 2 extra VPN-Servern machen.

**Comment by ghost** [comment]
Ack.

**Comment by oliver** [comment]
@SimJoSt dein PR #13 sieht für mich gut aus, und dein Vorschlag gefällt mir auch.

**Comment by genofire** [comment]
Ähm, nun nirgends vpn05 drin (und ich weiß auch nicht, wo ich vpn07 reinnehmen soll)
sollte der nicht in master drin sein (testing), aber noch nicht in (stable).

```
vpn05: 6cff5957231ca2936aabaa75ae5a7985f4077246b8956273b2ce2da559f344a9
vpn07: b0b24b08ae6764475e92c7a11192f39ce36b239b343b9670ceb274553ba0782e
```

**Comment by ghost** [comment]
Nein. Wie besprochen ist testing die Vorform von stable. Und da die Aussage von Jelto war, dass vpn05 nicht absehbar in die stable soll, ist er demnach auch nicht in der testing. Fuer Experimente kann ein experimental-Branch oder so erstellt werden (Irgendwie sowas gibts ja auch schon fuer irgendeiner Hardware-Revision 10 von irgendeinem Router).

**Comment by genofire** [comment]
Okay, ist also stable nun im master branch? (und wenn ja, wozu gibt es den stable branch?)

**Comment by SimJoSt** [comment]
@genofire 
Richtig, Firmware wird jetzt im master branch gebaut. Ob das dann stable oder testing ist, entscheidet nicht mehr der Code oder der Kompiliervorgang [1](http://bremen.freifunk.net/blog/2015/12/20/v2015-1-2-bremen3-und-firmwareschema-umstellung.html).
Der stable branch existiert noch, weil keiner ihn gelöscht hat. Reine Faulheit. Generell brauchen wir ihn nicht mehr.

**Comment by jplitza** [comment]
stable Branch ist gelöscht, Thema erledigt.
