### ISSUE TITLE
RFC: bandwidth_limit standard values

### ISSUE THREAD

**Issue by SimJoSt** [FreifunkBremen/gluon-site-ffhb#20]
Auf dem [Freifunk Bremen Treffen 17.02.2107](https://wiki.bremen.freifunk.net/Treffen/2017_02_17#protokoll_firmware) haben wir (@genofire, @timlukas, @Yannoik und @corny), zusätzlich zu dem Standardzustand von `Mesh-VPN` und `bandwidth_limit`, auch neue `egress` und `ìngress` Werte für `bandwidth_limit` besprochen.

Final hatten wir uns für die folgenden Werte entschieden:

    egress = 2000,
    ingress = 14000,

Diese Werte haben wir aufgrund der typischen, schmalen Internetverbindung an der man Freifunk evtl. drosseln will entschieden: 16.000. 8.000 ist zu schmal, als das Drosseln Sinn ergibt.
Für 16.000 sind 1.000 (Vodafone, 1und1) oder 2.000 (T-Kom, o2) typische Uploadraten. Idee war, einen kleinen Anteil zwischen 10% und 20% für das private Netzwerk zu reservieren. Für down fiel die Wahl auf 14.000, für up auf 2.000.
Mir ist aufgefallen, dass der zweite Wert nicht ansatzweise Sinn ergibt, da dann genau gar nichts reserviert wäre.

Also stelle ich die Werte hier noch mal zur Diskussion.
Schlagt Werte zwischen 80% und 90% vor und, ob wir uns an 1.000 oder 2.000 orientieren sollen:

Verbindung | 80% | 90%
--- | ---: | ---:
16.000 | 12.400 | 14.400
1.000 | 800 | 900
2.000 | 1.600 | 1.800

**Comment by SimJoSt** [comment]
Da ich die Aktivierung der Bandbreitenlimitierung mit Standard-Werten als eine "Panikaktion" unter der Premisse "ich will auf keinen Fall, dass Freifunk mir die ganze Bandbreite klaut" und ich noch nie reale Probleme mit Bandbreitenknappheit gesehen habe, würde ich zu einem möglichst hohen Wert tendieren. So kann Freifunk in den meisten Fällen besser funtkionieren.
Damit es rund aussieht hätte ich etwas rundes auf Tausenderstelle verwendet, da das aber bei up sowieso nicht geht können wir auch gleich die 90% nehmen.

Auch wenn die Standardlimits für Standardanschlüsse gedacht sind, hätte ich mich an 2.000 orientiert, da ich vermute, dass alle Anschlüsse in naher Zukunft in die Richtung "wachsen" werden, eine Limitierung beim Upload Freifunk mit seinem Grundrauschen möglicherweise massiv schaden könnte und der Upload in den meisten Fällen fast immer Kapazitäten über hat.

Ich bin also für:

    egress = 1800,
    ingress = 14400,

*Wer die Diskussion unnötig und pedantisch findet, möge bitte ein "mir egal" oder "go" schicken, damit wir uns nicht lange daran aufhalten :-)*

**Comment by ghost** [comment]
Das was SimJoSt sagt +1

lg
yannik

Am 19.02.2017 um 02:22 schrieb Simon Joda Stößer:

**Comment by Timi7007** [comment]
Kann zwar passieren, dass wir damit irgendwann Probleme bekommen (wenn jemand keine Ahnung hat und an einem wichtigen Ort den Upload soweit drosselt), aber aktuell ist das leider das Sinnvollste was wir tun können.

Also +1 für
~~~
egress = 1800,
ingress = 14400,
~~~

**Comment by SimJoSt** [comment]
implemented with https://github.com/FreifunkBremen/gluon-site-ffhb/commit/94be53cf44a712446fbe6bcf180d2a437f6e4365
