### ISSUE TITLE
rework of build.sh

### ISSUE THREAD

**Issue by SimJoSt** [FreifunkBremen/gluon-site-ffhb#21]
A few days ago we discussed reworking the build.sh and the readme needs to be updated as well as soon as that happen (there is already at least one mistake in it at the moment already).

I wanted to talk about in what way the build.sh should work in the future.
At the moment I was thinking it should:
- help build all targets at once
- automatically determine the release name

But other than that I am not sure what features to keep.
Discuss! :-)

**Comment by jplitza** [comment]
Nothing else. [The release name is automatically determined from the last tag in the site repo if none is given](https://github.com/FreifunkBremen/gluon-site-ffhb/blob/master/site.mk#L35), and the build.sh should use that.

Furthermore, with the switch to LEDE, `make clean` shouldn't be needed anymore before every new version build. So basically, the build.sh would then be
```sh
make update
for target in ...; do
  make -j $proc_num GLUON_TARGET="$target" GLUON_BRANCH=stable
done
make manifest GLUON_BRANCH=stable GLUON_PRIORITY=7
make manifest GLUON_BRANCH=testing GLUON_PRIORITY=0

# other stuff that is done in the current build.sh at the end
```

**Comment by SimJoSt** [comment]
make manifest GLUON_BRANCH=stable GLUON_PRIORITY=7
Is it possible to set the date of the stable.manifest to 2/3 weeks in the future? As this would normally be the release date for the stable?

    # other stuff that is done in the current build.sh at the end
Does this include the feature to continue a build (statefile) and the determination of the number of processors?

**Comment by jplitza** [comment]
Nope, using a future date isn't possible. [gluon/scripts/rfc3339date.lua](https://github.com/freifunk-gluon/gluon/blob/master/scripts/rfc3339date.lua) is used to generate the date, which always uses the current date. Maybe we should not generate a stable manifest at all?

And the determination of the number of threads to use has to happen before, and I assumed that to remain as indicated by the usage of `$proc_num`. My snippet wasn't supposed to be the whole new script, only the main commands.

The statefile stuff is obsolete if we no longer execute `make clean`.
