### ISSUE TITLE
v2017.1 branch - site.conf needs a site_seed

### ISSUE THREAD

**Issue by mablae** [FreifunkBremen/gluon-site-ffhb#25]
Like this: 
https://github.com/FreifunkVogtland/site-ffv/commit/a179bca07b003dd6aec42a28b8eca4a5b60335eb#diff-a3864532a8df90f563cd73bcf11f7af1R6

**Comment by jplitza** [comment]
This is only needed after 2017.1 and used for Mesh on (VX)LAN.
