### ISSUE TITLE
Gluon without wifi also build without respondd-module-airtime

### ISSUE THREAD

**Issue by genofire** [FreifunkBremen/gluon-site-ffhb#34]

**Comment by lokn** [comment]
Fürs Model UBNT-ERX wäre das super.
Sonst ist der Log nur mit Fehlern zu diesem Modul voll.

**Comment by jortgies** [comment]
> Fürs Model UBNT-ERX wäre das super.
> Sonst ist der Log nur mit Fehlern zu diesem Modul voll.

https://wiki.ffhb.de/Treffen/2020_01_03#tagesordnung_respondd-module-airtime-auf-er-x-entfernen

**Comment by genofire** [comment]
`'ubnt-erx', 'ubnt-erx'` und `'ubnt-erx-sfp', 'ubnt-erx-sfp'` - welche geräte noch?
