### ISSUE TITLE
offline SSID einführen

### ISSUE THREAD

**Issue by lokn** [FreifunkBremen/gluon-site-ffhb#35]
Problem:
Hat ein Knoten keinen Zugang zum Internet ist es für nicht-technische Nutzer des FFHB nicht klar, warum der Knoten kein Internet hat. Dies schadet dem Freifunk-Image und macht den Nutzer "offline".

Lösungsvorschlag:
Der Knoten überprüft regelmäßig ob eine Verbindung zum Internet besteht. Besteht diese nicht ändert der Knoten seine SSID von "bremen.freifunk.net" zu einer speziellen SSID die kommuniziert, dass keine Verbindung zum Internet besteht. Z.B. "Kein Internet FFHB".

Weitere Diskussion:
https://wiki.bremen.freifunk.net/Treffen/2019_12_06

**Comment by genofire** [comment]
Vorherige Implementierungen:
- [Breminale - Dienst by Ping](https://github.com/FreifunkBremen/ffhb-packages/blob/events/ffhb-breminale/files/sbin/watchdog)
- [Kieler - Cronjob by batman](https://github.com/freifunk-kiel/gluon-ssid-notifier/blob/lede/gluon-ssid-notifier/files/lib/gluon/ssid-notifier/ssid-notifier.sh)

---

Ich würde ungern die Kieler variante verwenden, da nicht zukunftssicher -> batman

Daher würde ich ein Cronjob ping vorschlagen, mit:
- lua setup wificonfig on upgrade [here](https://github.com/FreifunkBremen/ffhb-packages/blob/events/ffhb-breminale/files/lib/gluon/upgrade/320-watchdog-wlan)
- safety:
   - autoupdate is not running
   - hostapd exists
   - 3 minutes after boot

Nun die Diskussion, welche IP sollen wir anpingen (IPv6 geht nur).

Deine Meinung @jplitza ?

**Comment by Timi7007** [comment]
Der Vollständigkeit halber aus dem Protokoll vom [17.01.2020](https://wiki.bremen.freifunk.net/Treffen/2020_01_17#protokoll_offline-ssid):

### Offline-SSID
* Ergebnis einer Umfrage vom Workshop beim 36c3: Offline-SSID ist geil
* Abstimmung:
    * 1 Gegenstimme
    * 2 Enthaltung
    * 6 Stimmen dafür
* -> Ergebnis: wir wollen eine Offline-SSID
* Offene Fragen:
    * wie soll die Offline-SSID lauten? Vorschläge: offline.ffhb.de; ffhb-offline
    * wollen wir die Node-ID (oder so) in der Offline-SSID haben? Abstimmung: 8 dagegen; 0 dafür; 1 Enthaltung. Ergebnis: es wird eine einheitliche Offline-SSID auf allen FFHB-Knoten geben (nicht Knoten-abhängig)
    * welche IPv6-Adresse wollen wir anpingen? -> Idealerweise: mehrere Adressen (einige von FFHB, und z.B. was von Google)
    * wie lange soll es dauern, bis der Knoten in den Offline-Modus schaltet? Meinungen gehen auseinander (zwischen mehreren Minuten bis einer Stunde)
* idealerweise sollte das in einem Gluon-Modul implementiert werden, das dann Upstream gehen kann
* die Abfrage sollte nicht zu einer festen Zeit passieren, um das Netz nicht mit Peaks zu überlasten

**Comment by lokn** [comment]
Hier gibts noch einen anderen Ansatz: https://github.com/Freifunk-Nord/gluon-ssid-changer
Mit Aachener Firmware flüchtig getestet: funktioniert.

Wenn ich das richtig sehe, könnte es zukünftig ein Gluon-Paket dafür geben: https://github.com/freifunk-gluon/gluon/pull/1649

**Comment by genofire** [comment]
Der aktuelle Stand im PR ist aktuell noch Batman only ;(
Sieht aus, wie ich es gerne hätte ,(

Vvorausgesetzt es wird nun tatsächlich auf https://github.com/freifunk-gluon/gluon/pull/1684 aufgebaut und damit unabhängig von Batman.

---

Doch wenn es upstream was wird, bekommen wir es ohne großen Mehraufwand nicht vor dem Wechsel v2020.1 (BATMAN V) rein .... Wie sollen wir damit umgehen?

**Comment by lokn** [comment]
Bei mir läufts jetzt. Will das noch jemand testen?
@genofire, @jortgies Was sind die nächsten Schritte?

**Comment by genofire** [comment]
Der offline-ssid-changer hat noch größere Probleme mit DFS (wo ein client sich 1min nicht connecten kann) und co.
Bin mir daher nicht sicher, ob wir dieses package daher nur für die migration haben wollen.

Schritte:
- von mehr als eine Person testen lassen ( https://jenkins.bremen.freifunk.net/job/gluon-site-ffhb/176/artifact/gluon/output/images/ )
- patch in master übernehmen und testing bauen
- testing auf den nächsten treffen veröffentlichen

(oder wie sieht ihr es? Villt. kann man in der Testing das neue BatmanV-Netz schon als Auswahl mit anbieten)

**Comment by lokn** [comment]
merged in #45
