### ISSUE TITLE
[Test] Domainsplitt + 11s - Abnahme von v2019.1.1

### ISSUE THREAD

**Issue by genofire** [FreifunkBremen/gluon-site-ffhb#36]
- [x] update from v2019.1-bremen1
  - [x] erwartet domain `ffhb_legacy`
  - [x] mesh mit v2019.1
  - [x] mesh mit v2019.1.1 `ffhb_legacy`
  - [x] mesh NICHT mit v2019.1.1 `ffhb_11s`
- [x] new install v2019.1.1
  - [x] erwartet domain `ffhb_legacy`
  - [x] mesh mit v2019.1
  - [x] mesh mit v2019.1.1 `ffhb_legacy`
  - [x] mesh NICHT mit v2019.1.1 `ffhb_11s`
- [ ] change to `ffhb_11s` 
  - [x] ssh `uci set gluon.core.domain='ffhb_11s' && gluon-reconfigure && gluon-reload`
       (danke @hiaseilert )
    - [x] mesh NICHT mit v2019.1
    - [x] mesh NICHT mit v2019.1.1 `ffhb_legacy`
    - [x] mesh mit v2019.1.1 `ffhb_11s`
  - [x] Webgui - Setup-Modus
    - [x] mesh NICHT mit v2019.1
    - [x] mesh NICHT mit v2019.1.1 `ffhb_legacy`
    - [x] mesh mit v2019.1.1 `ffhb_11s`
  - [x] Zeitlicher Switch
    - [x] mesh NICHT mit v2019.1
    - [x] mesh NICHT mit v2019.1.1 `ffhb_legacy`
    - [x] mesh mit v2019.1.1 `ffhb_11s`
  - [ ] Offline Switch
    - [ ] mesh NICHT mit v2019.1
    - [x] mesh NICHT mit v2019.1.1 `ffhb_legacy`
    - [x] mesh mit v2019.1.1 `ffhb_11s`

**Comment by oliver** [comment]
Vorschlag:
* [ ] NTP auf dem Router deaktivieren, und dann die Systemzeit auf 6.3.2020 umschalten; dann testen, ob der automatische zeitgesteuerte Domain-Switch funktioniert

**Comment by hiaseilert** [comment]
Update auf v2019.1.1+bremen1 geht wie gewohnt, (mit `autoupdater -f`) in der uci config erscheint ein neuer Eintrag: gluon.core.domain='ffhb_legacy'
sonnst kein Änderungen mittels `uci show` feststellbar.

Umstellung zu ffhb_**11s zeigt keine Wirkung**. 

```
uci set gluon.core.domain='ffhb_11s'
uci commit gluon.core
reboot
uci show gluon.core.domain
gluon.core.domain='ffhb_11s'
```

nützt nichts, mesh´t weiterhin wie gewohnt mit v2019.1 und v2019.1.1

**Comment by genofire** [comment]
Danke für die Mühe, doch bitte Blogpost richtig lesen:
`uci set gluon.core.domain='ffhb_11s' && gluon-reconfigure && gluon-reload`

Magst du es mit dem `gluon-reconfigure` noch mal ausprobieren? Wäre echt hilfreich

**Comment by hiaseilert** [comment]
ok. Mir ist nicht aufgefallen das im Blogpost was anderes steht als hier.
`gluon-reconfigure && gluon-reload` hat funktioniert. danke.

Sieht jetzt alles gut aus.
Test der Neuinstallation und automatische Umstellung steht noch aus bei mir.

Zum Testen der Automatik: Reicht
```
uci set system.ntp.enabled='0'
uci commit system.ntp
date --set [TIME]
```
oder muss noch einen service gestoppt werden, um das Datum für ein par Tage manuell zu setzen?

**Comment by genofire** [comment]
Supi, sieht [hier](https://map.ffhb.de/#!/en/map/60e32793eb58) gut aus - danke fürs erneute testen.

Das mit den Zeiten ist genau die Frage, dass müsste meines Verständnisses ohne funktionieren.

**Comment by hiaseilert** [comment]
Das hat nicht gereicht. Ich teste [hier](https://map.ffhb.de/#!/en/map/18a6f74b9b36) gerade nochmal mit `/etc/init.d/sysntpd stop`.
Dort ist es jetzt (noch) der 04.03.

**Comment by genofire** [comment]
(05.03. ist die Umstellung - Versuch mal den 06.03 und warte ruhig eine Weile)

**Comment by hiaseilert** [comment]
Hab ich (mit 2020-03-05 12:48 hat auch gereicht). Ich lass den ...-SO ohne viel Spielerei da morgen von selbst reinlaufen.

**Comment by genofire** [comment]
@hiaseilert nice der Zeitswitcher hat funktioniert ;)

**Comment by hiaseilert** [comment]
Zeitlicher Switch getestet. Zum reproduzieren:

`cat /lib/gluon/release` # Version ist 2019.1+bremen1
`autoupdater -f`# update
`cat /lib/gluon/release` # Version ist 2019.1.1+bremen1

mesh verhalten beobachten.

NTP ausgeschaltet um manuel ein datum zu setzen.
`uci set system.ntp.enabled='0'`
`uci commit system.ntp`
`/etc/init.d/sysntpd stop`
`date --set '2020-03-04 23:50:00'` # Datum manuell setzen.

warten und mesh verhalten beobachten.

Nach Test: NTP wieder anschalten
`uci set system.ntp.enabled='1'`
`uci commit system.ntp`
`/etc/init.d/sysntpd start`

**Comment by hiaseilert** [comment]
Unter welchen Bedingungen greift der Offline Switch? Braucht es dazu ein bestimmtes datum?

**Comment by hiaseilert** [comment]
@genofire update from v2019.1-bremen1 mesh mit v2019.1.1 ffhb_legacy kannst du abharken.

**Comment by genofire** [comment]
ne nur eine `ffhb_legacy` der sein mesh verliert (und dadurch selbst offline ist - der sollte nach 2h selbst nach `ffhb_legacy` wechseln)

----

offtopic: gibt es eine Süßigkeit die du magst + bist am Freitag / nächstes Plenum da?

**Comment by hiaseilert** [comment]
### Test Offline Switch 
#### hias-TestNode02 (ssh)
v2019.1
mesh nur via Funk
`autoupdater -f` # update
`cat /lib/gluon/release` # auf 2019.1.1+bremen1

mesh't mit hias-TestNode04 2019.1+bremen1

#### hias-TestNode04 (ssh)
`autoupdater -f` # update
`cat /lib/gluon/release` # auf 2019.1.1+bremen1

hias-TestNode02 und hias-TestNode04 meshen erneut auf "ffhb_legacy"

ibss mesh auf 2,4Ghz ausschalten (Befehl weicht je nach Router model ab. `iwinfo` hilft :)
`uci set wireless.ibss_radio1.disabled='1'`
`wifi`

hias-TestNode02 ferliert mesh und ist offline.
... drei Stunden Später ...
#### hias-TestNode04 (ssh)
Wechsel zu ffhb_11s
`uci set gluon.core.domain='ffhb_11s' && gluon-reconfigure && gluon-reload`

hias-TestNode02 und hias-TestNode04 meshen erneut auf "ffhb_11s"
hias-TestNode02 hat den Wechsel selbständig gemacht und ist erreichbar.

#### Ergebnis
mesh NICHT mit v2019.1 ________________ Nicht getestet
mesh NICHT mit v2019.1.1 ffhb_legacy _ OK
mesh mit v2019.1.1 ffhb_11s _____________ OK

**Comment by oliver** [comment]
Hab grad mal eine komplette Neuinstallation getestet. Hab dazu einen fabrikneuen GL.iNet GL-AR150 ausgepackt und die aktuelle Testing-FW draufgeflasht.

Kommentare:
- im Config-Mode wird die "Domain"-Dropdownliste rot markiert; man muss etwas auswählen, um weiterzumachen - sehr schön. Wär noch interessant zu testen, was passiert, wenn man den Knoten jetzt einfach aus- und wieder einschaltet :-) kommt dann immer noch der Config-Modus hoch?
- die Namen der verfügbaren Domains erscheinen mir jetzt doch etwas schwer verständlich. Wenn jemand diese FW ganz neu und unbedarft verwendet, wie soll er dann eine Entscheidung treffen? ich glaub, wir sollten in den Namen das Umschaltdatum aufnehmen (also z.B. "Freifunk-Bremen mit IBSS-Mesh (nutzbar bis 5.3.2020)" und "Freifunk-Bremen mit 11s-Mesh (nutzbar ab 5.3.2020)".
- ich hab jetzt das IBSS-Mesh ausgewählt und neugestartet.

Ergebnisse:
- `cat /lib/gluon/release` ergibt `2019.1.1+bremen1`
- `uci show gluon.core.domain` ergibt `gluon.core.domain='ffhb_legacy'`
- Knoten mesht mit 2019.1+bremen1
- Knoten mesht mit 2019.1.1+bremen1 mit `ffhb_legacy`-Domain
- Knoten mesht NICHT mit 2019.1.1+bremen1 mit `ffhb_11s`-Domain (muss nachher noch schauen, dass der Testknoten tatsächlich 11s aktiviert hat. _Update:_ bin jetzt auf diesen weiteren Testknoten ebenfalls draufgekommen; der läuft in der Tat seit gestern erfolgreich im 11s-Modus)

- -> sieht erfolgreich aus; den Punkt "new install v2019.1.1" kannst du damit abhaken.

**Comment by oliver** [comment]
Hab jetzt den neu eingerichteten GL-AR150 über den Config-Mode (also die Web-GUI) auf 11s umgestellt.

Ergebnisse:
- Knoten ist per LAN-Kabel und Link-Local-IPv6 erreichbar (SSH und Status-Seite)
- `uci show gluon.core.domain` ergibt `gluon.core.domain='ffhb_11s`
- Knoten mesht NICHT mit v2019.1
- Knoten mesht NICHT mit v2019.1.1 mit ffhb_legacy
- Knoten mesht mit v2019.1.1 mit ffhb_11s (laut Statusseite)

**Comment by oliver** [comment]
Und beim Punkt "Offline Switch" kannst du den Unterpunkt "mesh NICHT mit v2019.1" jetzt auch abhaken: die beiden 11s-Knoten, die ich hier jetzt hab, meshen per Funk nicht mit 2019.1 (hab den einen jetzt per Kabel mit einem Stable-Knoten verbunden, damit die überhaupt online sind).

**Comment by hiaseilert** [comment]
Ich hab hier so ein TL-WR841N/ND v9
wenn der automatisch zu `ffhb_11s` gewechselt ist und der manuell wieder zu `ffhb_legacy` gemacht wurde. Ist es dann gewollt das er nicht von selbst zu `ffhb_11s` zurück wechselt, wenn alle in seiner Umgebung zu `ffhb_11s` migriert sind?

Ich hab her jetzt schon auf 11s umgestellt und aus spass mal mit Absicht von innen heraus umgestellt.

Nach 5h ist der äußere immer noch nicht im mesh.
Mit dem hab ich allerdings im Vorfeld schon mal den Zeitlichen switch getestet.

Der einzige unterschied zu den anderen test ist eigentlich dass er schon mal auf 11s war, schon mal in der Zukunft war und eine längere Laufzeit (4 Tagen) als bei den anderen tests hat.

Ich versuche das Zuhause noch mal nachzustellen. Ich hab noch ein 2019.1 und ein 2019.1.1 ffhb_legacy glaube ich. Lass die ein par Tage laufen und schalte den 2019.1 aus. Dann sollte der 2019.1.1 ffhb_legacy sich ja irgendwann bei den anderen im 11s mesh melden.

**Comment by genofire** [comment]
@hiaseilert ist er offline oder nochmal durch das zeitpunkt gelaufen?

falls du wer das manuelle ändert, selbstgemachtes leid, sry

**Comment by hiaseilert** [comment]
@genofire Der ist offline. Und hat die echte Zeit.

ok danke. Ging mir ums Verständnis.

**Comment by genofire** [comment]
okay, jetzt bin ich mir etwas unsicher ... frag dich am freitag aus okay?
