### ISSUE TITLE
SSH mit Passwort

### ISSUE THREAD

**Issue by genofire** [FreifunkBremen/gluon-site-ffhb#40]
In 2018.1 wurde eingeführt, das per default ssh nur noch mit ssh-keys funktioniert.
So wird es wieder angeschaltet: https://gluon.readthedocs.io/en/v2020.1.x/package/gluon-web-admin.html

Oder wollen wir es aus Sicherheitsgründen so lassen?
:+1: mit Passwort
:-1: ohne Password (nur SSH-Keys)

**Comment by MUHeinz** [comment]
+1 mit Passwort

**Comment by RadioBBS** [comment]
Dafür, Mindesvorgabe von Gluon sind 12 Zeichen.
