### ISSUE TITLE
Domain dropdown ausblenden

### ISSUE THREAD

**Issue by jortgies** [FreifunkBremen/gluon-site-ffhb#44]
siehe https://wiki.ffhb.de/Treffen/2020_04_17#freifunk-bremen-protokoll-pad_domainselector-louis

es sollte ausreichen `hide_domain = true` in die `ffhb_11s.conf` zu schreiben

**Comment by genofire** [comment]
Dann waehre keine Domain auswaehlbar ... sicher das dies funktioniert?
Vermutlich geht das nicht, bis wir domains wieder komplett abschalten (nach dem batman wechsel)

**Comment by jortgies** [comment]
> Dann waehre keine Domain auswaehlbar ... sicher das dies funktioniert?

grad getestet, stimmt leider...

hatte mir erhofft dass das dropdown feld verschwindet und man durch `default_domain = 'ffhb_11s'` nichts auswaehlen muss
